### PR TITLE
Fix exiting when not in a TTY over SSH

### PR DESCRIPTION
**Pull request by Tatsh**
Fixes #153 . When used over SSH or otherwise not in a TTY for a dump, Clutch will give minimal output. All calls to print to stdout/stderr will be on the main thread which simplifies closing these handles. Because the handles are closed, `sshd` will close the connection when Clutch finishes. Callers that use Clutch this way should just check the IPA (that it exists and can extract). The exit code is not affected by a failed dump.

There is surely a better solution, like making `GBPrint` and the like only use the main thread. But I have no really figured out the best way to do that just yet. It may require bringing back `CFRunLoopRun()` 😢 

Sorry, last PR was somewhat incomplete. All of `main.m` is fixed to have no `exit()` calls and retain all existing behaviour. Only change is exit codes are now 0, 1, 2, etc (no negative).

### CODE REVIEW

**Comment by ttwj** [comment]
Great, thanks for the help!

**Comment by NinjaLikesCheez** [comment]
You mention GBPrint - do you think it's use of fprintf in threads is holding up i/o/e file handles?

**Comment by Tatsh** [comment]
@NinjaLikesCheez no I'm almost certain it's actually the child Clutch processes. They run in the background, and when they exit, they don't let go of their stdout/stderr pipes, causing SSH to never drop the connection because it waits until *all* stderr/stdout handles are closed even if the process(es) exited.

**Comment by NinjaLikesCheez** [comment]
@Tatsh ok thank you, this could possibly/touch on relate to the ghost process issues people were also having.

**Pull request merged**
