### PR TITLE
Fix compilation problems

### PR DESCRIPTION
**Pull request by Razzile**
nothing major, just added ldid.mm to build sources

### CODE REVIEW

**Comment by Tatsh** [comment]
This fixes building for me.

**Comment by Tatsh** [comment]
@Razzile With your own signed build are you able to dump? My build still does not work. `ldid -S build/Release-iphoneos/Clutch` output:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>get-task-allow</key>
        <true/>
        <key>task_for_pid-allow</key>
        <true/>
        <key>com.apple.backboardd.debugapplications</key>
        <true/>
        <key>com.apple.springboard.debugapplications</key>
        <true/>
        <key>run-unsigned-code</key>
        <true/>
        <key>com.apple.private.librarian.can-get-application-info</key>
        <true/>
        <key>com.apple.private.mobileinstall.allowedSPI</key>
        <array>
                <string>Lookup</string>
                <string>CopyInstalledAppsForLaunchServices</string>
        </array>
</dict>
</plist>
```

Getting the error everyone else is getting, #103. iOS 8.4.

**Comment by alucard0134** [comment]
The issue is Clutch was trouble dumping the Watchkit portion of the app. You can dump apps without watchkit fine if you apply this fix, but you will still have issues with watchkit apps.

**Comment by kb** [comment]
@alucard0134 tried a build of this branch last night and still can't get a successful dump to occur. What version of iOS you are getting successful dumps for?

**Comment by Razzile** [comment]
@kb @Tatsh I think clutch fails now as it cannot retrieve a port for the epplication. An easy fix would be to create a dylib to inject into the application once running and dump the executable from the dylib because then a mach port isn't required

**Comment by NinjaLikesCheez** [comment]
I haven't tested this exact branch, but did the same thing on a local build and can get dumps of some apps on 8.4 arm64 only. A dylib was created a while back (not sure if it's in this repo or one locally) and I do plan on switching to this method at some point. This also makes ALSR stuff easier.

**Comment by iT0ny** [comment]
@NinjaLikesCheez yo! nice to have you back :)

**Pull request merged**
