### PR TITLE
Close stdin/stdout/stderr handles on child processes

### LINKED ISSUE #148: Clutch doesn't "exit" when run via SSH parameters
If running Clutch from inside an SSH session, it works fine and exits. However, if I use Clutch as parameter to SSH, it doesn't seem to quit. Ex: `ssh root@localhost Clutch -d 1`

When done this way, `Finished dumping com.app.bundle.id in x.x seconds` is printed but nothing happens after that and the `ssh` call doesn't exit. While the ssh call is still blocking, I tried opening another separate `ssh` session and checked `ps -ax` but Clutch process is no longer there. The only way to exit the blocking ssh call is to press Ctrl+C.

### PR DESCRIPTION
**Pull request by Tatsh**
Finally figured this out. Also tested on iOS 10.1.1 on iPhone 7 😎 

Fixes #148
Also this restores correct exit codes on failure (`1` on failure, `0` on success)

### CODE REVIEW

**Comment by NinjaLikesCheez** [comment]
I've merged this, however I've still noticed some issues on my 6s 9.3.3 locally - maybe the zip operations need the same treatment?

**Comment by Tatsh** [comment]
Which app is failing?

**Comment by Tatsh** [comment]
Just to note, the exit will not be immediate as the `-[NSOperationQueue cancelAllOperations]` still has to succeed. If that fails for some reason, really weird stuff will happen like ghost Clutch processes left behind especially which haven't been sent a signal to be killed.

To really fix that, if `-[BundleOperationDump cancel]` is invoked, the child PID must be known at that time (store it as a ivar?) and sent a SIGKILL to enforce its death.

The same thing must be done for any other child processes.

However, you may want a `SIGTERM` signal handler in Clutch that closes up the handles immediately and tries to exit. That way cancel call will close these up, and then you can send a `SIGKILL` signal just in case.

**Comment by NinjaLikesCheez** [comment]
Alien Blue, YouTube are the only two I've tested so far. Cracking succeeds (fully for AB, partial for YT), clutch exits but the sessions hangs still, even with some time given. I'll try test it on some more devices tonight and see what happens. 

Think `SIGTERM`/`SIGKILL` might be the way to go in the future.

**Comment by Tatsh** [comment]
Just to note, with latest master:

```
 $ scp -P 2222 Clutch/clutch root@localhost:~ && ssh -p 2222 root@localhost './clutch -d com.google.ios.youtube'
clutch                                                                                               100% 1204KB   1.2MB/s   00:00
Zipping YouTube.app
ASLR slide: 0x1000dc000
Dumping <NotificationServiceExtension> (arm64)
Patched cryptid (64bit segment)
Writing new checksum
ASLR slide: 0x100088000
Dumping <YouTube> (arm64)
Patched cryptid (64bit segment)
Writing new checksum
Zipping NotificationServiceExtension.appex
DONE: /private/var/mobile/Documents/Dumped/com.google.ios.youtube-iOS8.0-(Clutch-2.0.4).ipa
Finished dumping com.google.ios.youtube in 7.0 seconds
```

Hangs on 9.3.3, exits as expected on 10.1.1. So the problem isn't solved yet. I think this is a step in the right direction though.

**Comment by Tatsh** [comment]
Also, YouTube dumps on 10.1.1 but fails on iOS 9.3.3 anyway.

**Comment by Tatsh** [comment]
Testing on 9.3.3.

Need to unify the calls to `GBPrint`, `gbprintln`, `fprintf`, etc. Closing the handles to stdin/err/out at start of app or even after one call to `NSLog` makes the app quit properly over SSH. Yes it can be related to the child processes but setting `atexit_b()` with a block to close the handles at exit does not work. This should be a catch-all and really do it but it doesn't.

**Pull request merged**
